---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: check-ast
          - id: check-yaml
          - id: check-toml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-docstring-first
          - id: detect-private-key
          - id: fix-encoding-pragma
          - id: check-added-large-files
            args: [--maxkb=2000]
          - id: name-tests-test
            args: [--pytest-test-first]
          - id: requirements-txt-fixer

    - repo: https://github.com/psf/black
      rev: 23.11.0
      hooks:
          - id: black

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.16.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==22.3.0]

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-use-type-annotations
          - id: python-no-log-warn
          - id: python-check-blanket-noqa
          - id: python-check-mock-methods
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.33.0
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
            exclude: .github/workflows/.*|.circleci/.*


    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            args: [--width, '120']

    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
          - id: isort

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
          - id: bandit
            args: [-c, pyproject.toml]
            additional_dependencies: ['bandit[toml]']

    - repo: https://github.com/roy-ht/pre-commit-jupyter
      rev: v1.2.1
      hooks:
          - id: jupyter-notebook-cleanup
            args:
                - --remove-kernel-metadata
                - --pin-patterns
                - '[pin];[donotremove]'
