repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

#-   repo: https://github.com/PyCQA/isort
#    rev: 5.10.1  # Use the ref you want to point at
#    hooks:
#    -   id: isort
