---
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    python: circleci/python@2.1.1

jobs:
    build-and-test:
        # Change the version below to your required version of python
        docker:
            - image: cimg/python:3.10.9
        parallelism: 4
        steps:
            - checkout
            - python/install-packages:
                  pkg-manager: pipenv
                  args: --dev -e .
            - run:
                  name: Run tests
                  command: |
                      mkdir test-results
                      TESTFILES=$(circleci tests glob tests/test*.py | circleci tests split --split-by=timings)
                      pipenv run pytest --junitxml=test-results/junit.xml $TESTFILES
            - store_test_results:
                  path: test-results

workflows:
    tests:
        jobs:
            - build-and-test
