---
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    coveralls: coveralls/coveralls@1.0.6

jobs:
    build-and-test:
        # Change the version below to your required version of python
        machine:
            image: cimg/python:3.10.9-node
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                  name: Build Docker image
                  command: docker build . -t minerva:0.13 --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g)
            - run:
                  name: Run Docker image
                  command: |
                      docker run -it --mount "type=bind,src=$(pwd)/shared,dst=/opt/shared" \
                      --workdir /opt/sharedminerva:0.13 \
                      mkdir test-results && pytest --junitxml=test-results/junit.xml --cov-report=lcov:test-results/coverage.lcov
            - store_test_results:
                  path: test-results
            - store_artifacts:
                  path: test-results/coverage.lcov
                  destination: coverage
            - coveralls/upload:
                  path_to_lcov: test-results/coverage.lcov

workflows:
    tests:
        jobs:
            - build-and-test

# VS Code Extension Version: 1.5.1
