---
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    coveralls: coveralls/coveralls@1.0.6

jobs:
    build-and-test:
        # Change the version below to your required version of python
        docker:
            - image: cimg/python:3.10.9-node
              user: root
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: Build Docker image
                  command: docker build . -t minerva:latest
            - run:
                  name: Make directory for test results
                  command: mkdir -p /tmp/test-results
            - run:
                  name: Run Docker image
                  command: |
                      docker run --name minerva-runner -t minerva:latest \
                      pytest --junitxml=/tmp/test-results/junit.xml --cov-report=lcov:/tmp/test-results/coverage.lcov

            - run:
                  name: Copy test artifacts from container to host
                  command: |
                      docker cp minerva-runner:/tmp/test-results/junit.xml /tmp/test-results/junit.xml
                      docker cp minerva-runner:/tmp/test-results/coverage.lcov /tmp/test-results/coverage.lcov
            - store_test_results:
                  path: /tmp/test-results
            - store_artifacts:
                  path: /tmp/test-results/coverage.lcov
                  destination: coverage
            - coveralls/upload:
                  path_to_lcov: /tmp/test-results/coverage.lcov

workflows:
    tests:
        jobs:
            - build-and-test

# VS Code Extension Version: 1.5.1
