---
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
    # coveralls: solven/coveralls@0.0.4

jobs:
    build-and-test:
        # Change the version below to your required version of python
        docker:
            - image: docker:stable-git
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                  name: Build Docker image
                  command: docker build . -t minerva:0.13
            - run:
                  name: Run Docker image
                  command: docker run -n minerva:0.13
            - run:
                  name: Run tests
                  command: |
                      mkdir test-results
                      pytest --junitxml=test-results/junit.xml --cov-report=lcov:test-results/coverage.lcov
            - store_test_results:
                  path: test-results
            - store_artifacts:
                  path: test-results/coverage.lcov
                  destination: coverage

    # coverage:
    #     docker:
    #         - image: circleci/node:10.0.0
    #     steps:
    #         - checkout
    #         - run:
    #               name: Install and Make
    #               command: npm install && make test-coverage

    #         - coveralls/upload:
    #               path_to_lcov: test-results/coverage.lcov

workflows:
    tests:
        jobs:
            - build-and-test
            #- coverage

# VS Code Extension Version: 1.5.1
