---
# EXAMPLE MASTER CONFIG FILE

# === PATHS ===================================================================
dir:
    data:
        - tests
        - tmp
        - data
    configs:
        data_config: Chesapeake7.yml
        imagery_config: NAIP.yml
    results:
        - tests
        - tmp
        - results
    cache:
        - tests
        - tmp
        - cache

# ---+ Kwargs for make_datasets +----------------------------------------------
# Name of model. Substring before hyphen is model class.
model_name: FCN32ResNet50-MkI

# Type of model. Can be mlp, scene_classifier, segmentation.
model_type: segmentation

sample_pairs: false
elim: true
balance: true
patch_size: [256, 256]

# === DATASET PARAMETERS ======================================================
dataset_params:
    # Training Dataset
    train:
        imagery:
            module: torchgeo.datasets
            name: NAIP
            root: NAIP 2013/Train
            params:
                res: 1.0

        labels:
            module: torchgeo.datasets
            name: Chesapeake7
            root: Chesapeake
            params:
                res: 1.0
                download: false
                checksum: false

    # Validation Dataset
    val:
        imagery:
            module: torchgeo.datasets
            name: NAIP
            root: NAIP 2013/Validation
            params:
                res: 1.0

        labels:
            module: torchgeo.datasets
            name: Chesapeake7
            root: Chesapeake
            params:
                res: 1.0
                download: false
                checksum: false

    # Test Dataset
    test:
        imagery:
            module: torchgeo.datasets
            name: NAIP
            root: NAIP 2013/Test
            params:
                res: 1.0

        labels:
            module: torchgeo.datasets
            name: Chesapeake13
            root: Chesapeake
            params:
                res: 1.0
                download: false
                checksum: false

# === SAMPLER PARAMETERS ======================================================
sampler_params:
    # Training Dataset Sampler
    train:
        module: torchgeo.samplers
        name: RandomGeoSampler
        roi: false
        params:
            size: 256
            length: 80

    # Validation Dataset Sampler
    val:
        module: torchgeo.samplers
        name: RandomGeoSampler
        roi: false
        params:
            size: 256
            length: 32

    # Test Dataset Sampler
    test:
        module: torchgeo.samplers
        name: RandomGeoSampler
        roi: false
        params:
            size: 256
            length: 32


# === TRANSFORM PARAMETERS ====================================================
transform_params:
    # Training Dataset Transforms
    train:
        imagery: false
        labels: false

    # Validation Dataset Transforms
    val:
        imagery: false
        labels: false

    # Test Dataset Transforms
    test:
        imagery: false
        labels: false

# Collation
collator:
    module: torchgeo.datasets
    name: stack_samples

# Model hyper-parameters
hyperparams:
    params:
        batch_size: 16
        num_workers: 6
        pin_memory: true
    model_params:
        input_size: [4, 256, 256]
        n_classes: 16
    optim_name: SGD
    optim_params:
        lr: 1.0E-2
    loss_name: CrossEntropyLoss
    loss_params:
    max_epochs: 2

# Which plots to make
plots:
    History: true
    CM: true
    Pred: true
    ROC: true
    micro: false
    macro: true
    Mask: true

# opt to ask at runtime;
# auto or True to automatically do so;
# or False, None etc to not
save_model: false
run_tensorboard: false
save: true
show: false
p_dist: false
calc_norm: false
plot_last_epoch: false
