---
#       *       *    __  ________   ____________ _    _____
#   *        *      /  |/  /  _/ | / / ____/ __ \ |  / /   |  *           *
#       *          / /|_/ // //  |/ / __/ / /_/ / | / / /| |     *
#   *       *     / /  / // // /|  / /___/ _, _/| |/ / ___ |               *
#    *           /_/  /_/___/_/ |_/_____/_/ |_| |___/_/  |_|     *   *
#
#                          EXAMPLE MASTER CONFIG FILE
#
# === PATHS ===================================================================
dir:
    data: tests/tmp/data
    configs:
        data_config: Chesapeake7.yml
        imagery_config: NAIP.yml
    results: tests/tmp/results
    cache: tests/tmp/cache

# === HYPERPARAMETERS =========================================================
# ---+ Model Specification +---------------------------------------------------
# Name of model. Substring before hyphen is model class.
model_name: FCN32ResNet18-MkI

# Type of model. Can be mlp, scene_classifier, segmentation, ssl or siamese.
model_type: segmentation

# ---+ Sizing +----------------------------------------------------------------
batch_size: &batch_size 8             # Number of samples in each batch.
patch_size: &patch_size [32, 32]      # 2D tuple or float.
input_size: &input_size [4, 32, 32]   # patch_size plus leading channel dim.
max_epochs: &max_epochs 5             # Maximum number of training epochs.
n_classes: &n_classes 8               # Number of classes in dataset.

# ---+ Loss and Optimisers +---------------------------------------------------
loss_func: &loss_func CrossEntropyLoss  # Name of the loss function to use.
lr: &lr 1.0E-2                          # Learning rate of optimiser.
optim_func: &optim_func SGD             # Name of the optimiser function.

sample_pairs: false                   # Activates Siamese paired sampling.
elim: true                            # Eliminates empty classes from schema.
balance: true                         # Balances dataset classes.
pre_train: false                      # Activate pre-training mode.
fine_tune: false                      # Activate fine-tuning mode.

# ---+ Model Paramets +--------------------------------------------------------
model_params:
    input_size: *input_size
    n_classes: *n_classes
    # any other params...

# ---+ Optimiser Parameters +--------------------------------------------------
optim_params:
    name: *optim_func
    params:
        lr: *lr

# ---+ Loss Function Parameters +----------------------------------------------
loss_params:
    name: *loss_func
    params:

# ---+ Dataloader Parameters +-------------------------------------------------
loader_params:
    batch_size: *batch_size
    num_workers: 1
    pin_memory: true

# === WANDB LOGGING ===========================================================
wandb_log: true
project: pytest
wandb_dir: /test/tmp/wandb

# === MODEL IO & LOGGING ======================================================
# ---+ Minerva Inbuilt Logging Functions +-------------------------------------
logger: STGLogger
metrics: SPMetrics
model_io: sup_tg

record_int: true
record_float: true

# ---+ Collator +--------------------------------------------------------------
collator:
    module: torchgeo.datasets
    name: stack_samples

# === DATASET PARAMETERS ======================================================
dataset_params:
    # Training Dataset
    train:
        image:
            images_1:
                module: minerva.datasets
                name: TstImgDataset
                root: test_images
                params:
                    res: 1.0

            image2:
                module: minerva.datasets
                name: TstImgDataset
                root: test_images
                params:
                    res: 1.0

        mask:
            module: minerva.datasets
            name: TstMaskDataset
            root: test_lc
            params:
                res: 1.0

    # Validation Dataset
    val:
        image:
            module: minerva.datasets
            name: TstImgDataset
            root: test_images
            params:
                res: 1.0

        mask:
            module: minerva.datasets
            name: TstMaskDataset
            root: test_lc
            params:
                res: 1.0

    # Test Dataset
    test:
        image:
            module: minerva.datasets
            name: TstImgDataset
            root: test_images
            params:
                res: 1.0

        mask:
            module: minerva.datasets
            name: TstMaskDataset
            root: test_lc
            params:
                res: 1.0

# === SAMPLER PARAMETERS ======================================================
sampler_params:
    # Training Dataset Sampler
    train:
        module: torchgeo.samplers
        name: RandomGeoSampler
        roi: false
        params:
            size: *patch_size
            length: 120

    # Validation Dataset Sampler
    val:
        module: torchgeo.samplers
        name: RandomGeoSampler
        roi: false
        params:
            size: *patch_size
            length: 32

    # Test Dataset Sampler
    test:
        module: torchgeo.samplers
        name: RandomGeoSampler
        roi: false
        params:
            size: *patch_size
            length: 32

# === TRANSFORM PARAMETERS ====================================================
transform_params:
    # Training Dataset Transforms
    train:
        image: false
        mask: false

    # Validation Dataset Transforms
    val:
        image: false
        mask: false

    # Test Dataset Transforms
    test:
        image: false
        mask: false

# === PLOTTING OPTIONS ========================================================
plots:
    History: true
    CM: true
    Pred: true
    ROC: true
    micro: true
    macro: true
    Mask: true

# === MISCELLANEOUS OPTIONS ===================================================
# ---+ Early Stopping +--------------------------------------------------------
stopping:
    patience: 2    # No. of val epochs with increasing loss before stopping.
    verbose: true  # Verbosity of early stopping prints to stdout.

# ---+ Verbosity and Saving +--------------------------------------------------
verbose: true           # Verbosity of Trainer print statements to stdout.
save: true              # Saves created figures to file.
show: false             # Shows created figures in a pop-up window.
p_dist: true            # Shows the distribution of classes to stdout.
plot_last_epoch: true   # Plot the results of the last training and val epochs.

# opt to ask at runtime; auto or True to automatically do so; or False,
# None etc to not
save_model: true

# ---+ Other +-----------------------------------------------------------------
# opt to ask at runtime; auto or True to automatically do so; or False,
# None etc to not
run_tensorboard: false
calc_norm: false
