---
# EXAMPLE MANIFEST CONFIG FILE

# === PATHS ===================================================================
dir:
    data:
        - tests
        - tmp
        - data
    configs:
        data_config: ../../config/Chesapeake7.yml
    output:
        - tests
        - tmp
        - cache

# === DATASET PARAMETERS ======================================================
dataset_params:
    imagery:
        module: minerva.datasets
        name: TestImgDataset
        root: test_images
        params:
            res: 10.0
    labels:
        module: minerva.datasets
        name: TestMaskDataset
        root: test_lc
        params:
            res: 10.0


# === SAMPLER PARAMETERS ======================================================
sampler_params:
    module: torchgeo.samplers
    name: GridGeoSampler
    params:
        size: [1000, 1000]
        stride: [1000, 1000]

collator:
    module: torchgeo.datasets
    name: stack_samples

# Dataloader
dataloader_params:
    batch_size: 8
    num_workers: 4
    pin_memory: false
