# EXAMPLE MANIFEST CONFIG FILE

# === PATHS ===========================================================================================================
dir:
  data:
    - ''
    - 'mnt'
    - 'c'
    - 'Users'
    - 'hjb1d20'
    - 'Repositories'
    - 'Minerva'
    - 'data'
  configs:
    data_config: '../../config/Chesapeake13.yml'
    imagery_config: '../../config/landcovernet.yml'
  output:
    - ''
    - 'mnt'
    - 'c'
    - 'Users'
    - 'hjb1d20'
    - 'Repositories'
    - 'Minerva'
    - 'cache'

# === DATASET PARAMETERS ==============================================================================================
dataset_params:
  imagery:
    module: 'torchgeo.datasets'
    name: 'NAIP'
    root: 'NAIP 2013'
    params:
      res: 1.0
  labels:
    module: 'torchgeo.datasets'
    name: 'Chesapeake13'
    root: 'Chesapeake'
    params:
      res: 1.0
      download: False
      checksum: False
  

# === SAMPLER PARAMETERS ==============================================================================================
sampler_params:
  module: 'torchgeo.samplers'
  name: 'GridGeoSampler'
  params:
    size: [1000, 1000]
    #length: 10000
    stride: [1000, 1000]

collator:
  module: 'torchgeo.datasets'
  name: 'stack_samples'

# Dataloader
dataloader_params:
  batch_size: 8
  num_workers: 4
  pin_memory: False
