---
# Paths to directories containing the data and the results
dir:
    data:
        - 'G:'
        - GitHub
        - Minerva
        - Minerva
        - data
        - landcovernet
    data_config: ../../config/ESRI.yml
    imagery_config: ../../config/landcovernet.yml
    results:
        - 'F:'
        - Harry
        - University
        - Postgraduate
        - Output Plots
        - MinervaPercep
        - MLP

# Model Name
model_name: MLP-MkVIII
model_type: MLP

elim: true
scene_selector: ref
centre_only: false
balance: true

# Model hyper-parameters
hyperparams:
    params:
        batch_size: 256
        num_workers: 5
        pin_memory: true
    model_params:
        input_size: 288
        n_classes: 11
        hidden_sizes: [512, 1024, 256]
    optim_name: SGD
    optim_params:
        lr: 3.0E-4
    loss_name: CrossEntropyLoss
    loss_params:
    max_epochs: 15

# Settings for RGB image creation
rgb_params:
    band_ID: SCL           # 3 char alpha-numeric Band ID
    R_band: B02            # Red, Green, Blue band IDs for RGB images
    G_band: B03
    B_band: B04
