---
# Paths to directories containing the data and the results
dir:
    data:
        - 'G:'
        - GitHub
        - Minerva
        - Minerva
        - data
        - landcovernet
    data_config: ../../config/ESRI.yml
    imagery_config: ../../config/landcovernet.yml
    results:
        - 'F:'
        - Harry
        - University
        - Postgraduate
        - Output Plots
        - MinervaPercep
        - ResNet

# Model Name
model_name: ResNet18-MkII
model_type: CNN

elim: true
scene_selector: threshold
centre_only: false
balance: true
over_factor: 15

# Model hyper-parameters
hyperparams:
    params:
        batch_size: 32
        num_workers: 8
        pin_memory: true
    model_params:
        input_size: [12, 256, 256]
        n_classes: 11
    optim_name: SGD
    optim_params:
        lr: 0.5E-4
    # momentum: 0.9
    loss_name: CrossEntropyLoss
    loss_params:
    transforms:
    max_epochs: 10

# Settings for RGB image creation
rgb_params:
    band_ID: SCL           # 3 char alpha-numeric Band ID
    R_band: B02            # Red, Green, Blue band IDs for RGB images
    G_band: B03
    B_band: B04
