# Paths to directories containing the data and the results
dir:
  data:
   - 'G:'
   - 'GitHub'
   - 'Minerva'
   - 'Minerva'
   - 'data'
   - 'landcovernet'
  configs:
    data_config: '../../config/ESRI.yml'
    imagery_config: '../../config/landcovernet.yml'
  results:
    - 'F:'
    - 'Harry'
    - 'University'
    - 'Postgraduate'
    - 'OneDrive - University of Southampton'
    - 'Output Plots'
    - 'MinervaPercep'
    - 'FCNResNet'

# Kwargs for make_datasets
model_name: 'FCN32ResNet18-MkI' # Name of model. Substring before hyphen is used to find and initialise model object.
model_type: 'segmentation'      # Type of model. Can be mlp, scene_classifier, segmentation.
frac: 0.5                       # Fraction of patches in the dataset to use.
split: [0.8, 0.15, 0.05]        # Fractional size of the train, validation and test datasets.
elim: True
scene_selector: 'threshold'
centre_only: False
balance: True

# Model hyper-parameters
hyperparams:
  params:
    batch_size: 16
    num_workers: 10
    pin_memory: True
  model_params:
    input_size: [6, 256, 256]
    n_classes: 11
    #groups: 32
    #width_per_group: 4
    #batch_size: 16
  optim_name: SGD
  optim_params:
    lr: 1.0E-2
    #momentum: 0.9
  loss_name: CrossEntropyLoss
  loss_params:
  transforms:
    #CenterCrop:
      #size: 128
  max_epochs: 5

# Which plots to make
plots:
  History: True
  CM: True
  Pred: True
  ROC: False
  Mask: True
  PvT: False

# opt to ask at runtime; auto or True to automatically do so; or False, None etc to not
save_model: False
run_tensorboard: False
save: True
show: False
p_dist: False

# Settings for RGB image creation
rgb_params:
  band_ID: 'SCL'           # 3 char alpha-numeric Band ID
  R_band: 'B02'            # Red, Green, Blue band IDs for RGB images
  G_band: 'B03'
  B_band: 'B04'
