# Paths to directories containing the data and the results
dir:
  data:
   - 'G:'
   - 'GitHub'
   - 'Minerva'
   - 'Minerva'
   - 'data'
   - 'landcovernet'
  configs:
    data_config: '../../config/ESRI.yml'
    imagery_config: '../../config/landcovernet.yml'
  results:
    - 'F:'
    - 'Harry'
    - 'University'
    - 'Postgraduate'
    - 'OneDrive - University of Southampton'
    - 'Output Plots'
    - 'MinervaPercep'
    - 'FCNResNet'

# Kwargs for make_datasets
model_name: 'FCN8ResNet50-TEST' # Name of model. Substring before hyphen is used to find and initialise model object.
model_type: 'segmentation'      # Type of model. Can be mlp, cnn, segmentation.
frac: 0.05                      # Fraction of patches in the dataset to use.
elim: True
scene_selector: 'threshold'
centre_only: False
balance: True

# Model hyper-parameters
hyperparams:
  params:
    batch_size: 16
    num_workers: 10
    pin_memory: True
  model_params:
    input_size: [6, 256, 256]
    n_classes: 11
    #groups: 32
    #width_per_group: 4
  optim_name: SGD
  optim_params:
    lr: 1.0E-2
    #momentum: 0.9
  loss_name: CrossEntropyLoss
  loss_params:
  transforms:
    #CenterCrop:
      #size: 128
  max_epochs: 2

# Which plots to make
plots:
  History: False
  CM: False
  Pred: False
  Mask: False
  PvT: False

save_model: 'opt'
run_tensorboard: 'opt'

# Settings for RGB image creation
rgb_params:
  band_ID: 'SCL'           # 3 char alpha-numeric Band ID
  R_band: 'B02'            # Red, Green, Blue band IDs for RGB images
  G_band: 'B03'
  B_band: 'B04'
