# Paths to directories containing the data and the results
dir:
  data: '../../data/landcovernet'
  data_config: '../../config/landcovernet.yml'
  results:
    - 'F:'
    - 'Harry'
    - 'University'
    - 'Postgraduate'
    - 'Output Plots'
    - 'MinervaPercep'
    - 'MLP'

# Model Name
model_name: 'MLP-MkVI'

# Model hyper-parameters
hyperparams:
  params:
    batch_size: 256
    num_workers: 3
    pin_memory: True
  model_params:
    input_size: 288
    n_classes: 8
    hidden_sizes: [512, 256]
  optimiser_params:
    optimiser: SGD
    learning_rate: 3.0E-4
    momentum: None
  max_epochs: 7

# Settings for RGB image creation
rgb_params:
  band_ID: 'SCL'           # 3 char alpha-numeric Band ID
  R_band: 'B02'            # Red, Green, Blue band IDs for RGB images
  G_band: 'B03'
  B_band: 'B04'
