# EXAMPLE MASTER CONFIG FILE

# === PATHS ===========================================================================================================
dir:
  data:
   - 'G:'
   - 'GitHub'
   - 'Minerva'
   - 'Minerva'
   - 'data'
   - 'landcovernet'
  configs:
    data_config: '../../config/ESRI.yml'
    imagery_config: '../../config/landcovernet.yml'
  results:
    - 'F:'
    - 'Harry'
    - 'University'
    - 'Postgraduate'
    - 'OneDrive - University of Southampton'
    - 'Output Plots'
    - 'MinervaPercep'
    - 'FCNResNet'

# Kwargs for make_datasets
model_name: 'FCN32ResNet50-MkI' # Name of model. Substring before hyphen is used to find and initialise model object.
model_type: 'segmentation'      # Type of model. Can be mlp, scene_classifier, segmentation.
frac: 1.0                       # Fraction of patches in the dataset to use.
split: [0.8, 0.15, 0.05]        # Fractional size of the train, validation and test datasets.
elim: False
balance: False
patch_size: [56, 56]

# === DATASET PARAMETERS ==============================================================================================
dataset_params:
  # Training Dataset
  train:
    imagery:
      module: 'torchgeo.datasets'
      name: 'NAIP'
      root: 'NAIP'
      params:
        crs: None
        #download: True
        #checksum: True
        #splits: ['ny-train', 'de-train', 'md-train', 'wv-train', 'va-train', 'pa-train']
        #layers: ['naip-new', 'lc']
    labels:
      module: 'torchgeo.datasets'
      name: 'ChesapeakeDE'
      root: 'DE'
      params:
        download: False
        checksum: False
        #splits: ['ny-train', 'de-train', 'md-train', 'wv-train', 'va-train', 'pa-train']
        #layers: ['naip-new', 'lc']

  # Validation Dataset
  val:
    imagery:
      module: 'torchgeo.datasets'
      name: 'NAIP'
      root: 'NAIP'
      params:
        res: None
        #download: False
        #checksum: False
        #splits: ['ny-train', 'de-train', 'md-train', 'wv-train', 'va-train', 'pa-train']
        #layers: ['naip-new', 'lc']
    labels:
      module: 'torchgeo.datasets'
      name: 'ChesapeakeDE'
      root: 'DE'
      params:
        download: False
        checksum: False
        #splits: ['ny-train', 'de-train', 'md-train', 'wv-train', 'va-train', 'pa-train']
        #layers: ['naip-new', 'lc']

  # Test Dataset
  test:
    imagery:
      module: 'torchgeo.datasets'
      name: 'NAIP'
      root: 'NAIP'
      params:
        res: None
        #download: False
        #checksum: False
        #splits: ['ny-train', 'de-train', 'md-train', 'wv-train', 'va-train', 'pa-train']
        #layers: ['naip-new', 'lc']
    labels:
      module: 'torchgeo.datasets'
      name: 'ChesapeakeDE'
      root: 'DE'
      params:
        download: False
        checksum: False
        #splits: ['ny-train', 'de-train', 'md-train', 'wv-train', 'va-train', 'pa-train']
        #layers: ['naip-new', 'lc']

# === SAMPLER PARAMETERS ==============================================================================================
sampler_params:
  # Training Dataset Sampler
  train:
    module: 'torchgeo.samplers'
    name: 'RandomGeoSampler'
    params:
      size: 56
      #batch_size: 16
      length: 1600

  # Validation Dataset Sampler
  val:
    module: 'torchgeo.samplers'
    name: 'RandomGeoSampler'
    params:
      size: 56
      #batch_size: 16
      length: 400

  # Test Dataset Sampler
  test:
    module: 'torchgeo.samplers'
    name: 'RandomGeoSampler'
    params:
      size: 56
      #batch_size: 16
      length: 400


# === TRANSFORM PARAMETERS ============================================================================================
transform_params:
  # Training Dataset Transforms
  train:
    imagery:
      ConvertImageDtype: torch.FloatTensor
    labels:
      ConvertImageDtype: torch.LongTensor

  # Validation Dataset Transforms
  val:
    imagery:
      ConvertImageDtype: torch.FloatTensor
    labels:
      ConvertImageDtype: torch.LongTensor

  # Test Dataset Transforms
  test:
    imagery:
      ConvertImageDtype: torch.FloatTensor
    labels:
      ConvertImageDtype: torch.LongTensor

# Collation
collator:
  module: 'torchgeo.datasets'
  name: 'stack_samples'

# Model hyper-parameters
hyperparams:
  params:
    batch_size: 16
    num_workers: 6
    pin_memory: True
  model_params:
    input_size: [4, 56, 56]
    n_classes: 16
    #groups: 32
    #width_per_group: 4
    #batch_size: 16
  optim_name: SGD
  optim_params:
    lr: 1.0E-2
    #momentum: 0.9
  loss_name: CrossEntropyLoss
  loss_params:
  max_epochs: 20

# Which plots to make
plots:
  History: True
  CM: True
  Pred: True
  ROC: True
  micro: False
  macro: True
  Mask: True
  PvT: False

# opt to ask at runtime; auto or True to automatically do so; or False, None etc to not
save_model: False
run_tensorboard: False
save: True
show: False
p_dist: False
calc_norm: False
plot_last_epoch: True

# Settings for RGB image creation
#rgb_params:
#  band_ID: 'SCL'           # 3 char alpha-numeric Band ID
#  R_band: 'B02'            # Red, Green, Blue band IDs for RGB images
#  G_band: 'B03'
#  B_band: 'B04'
