# Paths to directories containing the data and the results
dir:
  data: '../../data/landcovernet'
  data_config: '../../config/landcovernet.yml'
  results:
    - 'F:'
    - 'Harry'
    - 'University'
    - 'Postgraduate'
    - 'Output Plots'
    - 'MinervaPercep'
    - 'ResNet'

# Model Name
model_name: 'ResNet18-MkI'

elim: True

scene_selector: 'threshold'

# Model hyper-parameters
hyperparams:
  params:
    batch_size: 16
    num_workers: 10
    pin_memory: True
  model_params:
    input_shape: [12, 256, 256]
    n_classes: 8
  optim_name: SGD
  optim_params:
    lr: 3.0E-4
    momentum: 0.9
  loss_name: CrossEntropyLoss
  loss_params:
  transforms:
    #CenterCrop:
      #size: 128
  max_epochs: 25

# Settings for RGB image creation
rgb_params:
  band_ID: 'SCL'           # 3 char alpha-numeric Band ID
  R_band: 'B02'            # Red, Green, Blue band IDs for RGB images
  G_band: 'B03'
  B_band: 'B04'
