---
# EXAMPLE MANIFEST CONFIG FILE

# === PATHS ===================================================================
dir:
    data:
        - tests
        - fixtures
        - data
    configs:
        data_config: minerva/inbuilt_cfgs/Chesapeake7.yml
    output:
        - tests
        - tmp
        - cache

# === DATASET PARAMETERS ======================================================
dataset_params:
    make:
        image:
            module: minerva.datasets.__testing
            name: TestImgDataset
            paths: NAIP
            params:
                res: 1.0
        mask:
            module: minerva.datasets.__testing
            name: TestMaskDataset
            paths: Chesapeake7
            params:
                res: 1.0


# === SAMPLER PARAMETERS ======================================================
sampler_params:
    make:
        module: torchgeo.samplers
        name: GridGeoSampler
        params:
            size: [1000, 1000]
            stride: [1000, 1000]

collator:
    module: torchgeo.datasets
    name: stack_samples

# Dataloader
dataloader_params:
    batch_size: 8
    num_workers: 4
    pin_memory: false
