---
name: tests 🧪

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.10', '3.11', '3.12']
                exclude:
                    - os: windows-latest
                      python-version: '3.12'

        steps:
            - name: Support longpaths
              run: git config --global core.longpaths true
            - uses: actions/checkout@v4
            - name: Test Py ${{ matrix.python-version }} 🧪
              uses: collective/tox-action@main
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Upload coverage report to CodeCov ☂
              uses: codecov/codecov-action@v4
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
