---
name: tests

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                python-version: ['3.8', '3.9', '3.10', '3.11']

        steps:
            - uses: actions/checkout@v3
            - name: Test Py ${{ matrix.python-version }}
              uses: collective/tox-action@main
              with:
                  python-version: ${{ matrix.python-version }}
